server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  #下面时配置动态路由的内容
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: payment_routh
          uri: lb://cloud-payment-service #匹配提供服务的路由地址
          predicates:
            - Path=/payment/get/**

        - id: payment_routh2
          uri: lb://cloud-payment-service #匹配提供服务的路由地址
          predicates:
            - Path=/payment/lb/**
            #- After=2020-12-15T20:09:16.589+08:00[Asia/Shanghai]
            #- Cookie=username,zzyy
            #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性，并且值为整数的正则表达式
  #普通内容
  #cloud:
  #  gateway:
  #    routes:
  #      - id: payment_routh #payment_route   路由的ID，没有固定规则，但要求唯一，建议配合服务名
  #        uri: http://localhost:8001  #匹配后提供服务的路由地址
  #        predicates:
  #          - Path=/payment/get/**    #断言，路径相匹配的进行路由

  #      - id: payment_routh2 #payment_route
  #        uri: http://localhost:8001
  #        predicates:
  #          - Path=/payment/lb/**   #断言，路径相匹配，则进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider，注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true #表示是否从eureka获取到注册信息
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka